package io.github.wsyong11.gameforge.framework.system.graphic.vulkan.ex;

import com.google.common.collect.ImmutableMap;
import io.github.wsyong11.gameforge.util.number.Hex;
import org.jetbrains.annotations.NotNull;

import java.util.Locale;
import java.util.Map;
import java.util.Set;

import static org.lwjgl.vulkan.EXTDebugReport.VK_ERROR_VALIDATION_FAILED_EXT;
import static org.lwjgl.vulkan.EXTFullScreenExclusive.VK_ERROR_FULL_SCREEN_EXCLUSIVE_MODE_LOST_EXT;
import static org.lwjgl.vulkan.EXTImageCompressionControl.VK_ERROR_COMPRESSION_EXHAUSTED_EXT;
import static org.lwjgl.vulkan.EXTImageDrmFormatModifier.VK_ERROR_INVALID_DRM_FORMAT_MODIFIER_PLANE_LAYOUT_EXT;
import static org.lwjgl.vulkan.EXTShaderObject.VK_INCOMPATIBLE_SHADER_BINARY_EXT;
import static org.lwjgl.vulkan.KHRDeferredHostOperations.*;
import static org.lwjgl.vulkan.KHRDisplaySwapchain.VK_ERROR_INCOMPATIBLE_DISPLAY_KHR;
import static org.lwjgl.vulkan.KHRPipelineBinary.VK_ERROR_NOT_ENOUGH_SPACE_KHR;
import static org.lwjgl.vulkan.KHRPipelineBinary.VK_PIPELINE_BINARY_MISSING_KHR;
import static org.lwjgl.vulkan.KHRSurface.VK_ERROR_NATIVE_WINDOW_IN_USE_KHR;
import static org.lwjgl.vulkan.KHRSurface.VK_ERROR_SURFACE_LOST_KHR;
import static org.lwjgl.vulkan.KHRSwapchain.VK_ERROR_OUT_OF_DATE_KHR;
import static org.lwjgl.vulkan.KHRSwapchain.VK_SUBOPTIMAL_KHR;
import static org.lwjgl.vulkan.KHRVideoEncodeQueue.VK_ERROR_INVALID_VIDEO_STD_PARAMETERS_KHR;
import static org.lwjgl.vulkan.KHRVideoQueue.*;
import static org.lwjgl.vulkan.NVGLSLShader.VK_ERROR_INVALID_SHADER_NV;
import static org.lwjgl.vulkan.VK10.*;
import static org.lwjgl.vulkan.VK11.VK_ERROR_INVALID_EXTERNAL_HANDLE;
import static org.lwjgl.vulkan.VK11.VK_ERROR_OUT_OF_POOL_MEMORY;
import static org.lwjgl.vulkan.VK12.VK_ERROR_FRAGMENTATION;
import static org.lwjgl.vulkan.VK12.VK_ERROR_INVALID_OPAQUE_CAPTURE_ADDRESS;
import static org.lwjgl.vulkan.VK13.VK_PIPELINE_COMPILE_REQUIRED;
import static org.lwjgl.vulkan.VK14.VK_ERROR_NOT_PERMITTED;

public class VkResultUtil {
	private static final Map<Integer, String> NAMES = ImmutableMap
		.<Integer, String>builder()
		.put(VK_SUCCESS, "VK_SUCCESS")
		.put(VK_NOT_READY, "VK_NOT_READY")
		.put(VK_TIMEOUT, "VK_TIMEOUT")
		.put(VK_EVENT_SET, "VK_EVENT_SET")
		.put(VK_EVENT_RESET, "VK_EVENT_RESET")
		.put(VK_INCOMPLETE, "VK_INCOMPLETE")
		.put(VK_ERROR_OUT_OF_HOST_MEMORY, "VK_ERROR_OUT_OF_HOST_MEMORY")
		.put(VK_ERROR_OUT_OF_DEVICE_MEMORY, "VK_ERROR_OUT_OF_DEVICE_MEMORY")
		.put(VK_ERROR_INITIALIZATION_FAILED, "VK_ERROR_INITIALIZATION_FAILED")
		.put(VK_ERROR_DEVICE_LOST, "VK_ERROR_DEVICE_LOST")
		.put(VK_ERROR_MEMORY_MAP_FAILED, "VK_ERROR_MEMORY_MAP_FAILED")
		.put(VK_ERROR_LAYER_NOT_PRESENT, "VK_ERROR_LAYER_NOT_PRESENT")
		.put(VK_ERROR_EXTENSION_NOT_PRESENT, "VK_ERROR_EXTENSION_NOT_PRESENT")
		.put(VK_ERROR_FEATURE_NOT_PRESENT, "VK_ERROR_FEATURE_NOT_PRESENT")
		.put(VK_ERROR_INCOMPATIBLE_DRIVER, "VK_ERROR_INCOMPATIBLE_DRIVER")
		.put(VK_ERROR_TOO_MANY_OBJECTS, "VK_ERROR_TOO_MANY_OBJECTS")
		.put(VK_ERROR_FORMAT_NOT_SUPPORTED, "VK_ERROR_FORMAT_NOT_SUPPORTED")
		.put(VK_ERROR_FRAGMENTED_POOL, "VK_ERROR_FRAGMENTED_POOL")
		.put(VK_ERROR_UNKNOWN, "VK_ERROR_UNKNOWN")
		.put(VK_ERROR_OUT_OF_POOL_MEMORY, "VK_ERROR_OUT_OF_POOL_MEMORY")
		.put(VK_ERROR_INVALID_EXTERNAL_HANDLE, "VK_ERROR_INVALID_EXTERNAL_HANDLE")
		.put(VK_ERROR_FRAGMENTATION, "VK_ERROR_FRAGMENTATION")
		.put(VK_ERROR_INVALID_OPAQUE_CAPTURE_ADDRESS, "VK_ERROR_INVALID_OPAQUE_CAPTURE_ADDRESS")
		.put(VK_PIPELINE_COMPILE_REQUIRED, "VK_PIPELINE_COMPILE_REQUIRED")
		.put(VK_ERROR_NOT_PERMITTED, "VK_ERROR_NOT_PERMITTED")
		.put(VK_ERROR_SURFACE_LOST_KHR, "VK_ERROR_SURFACE_LOST_KHR")
		.put(VK_ERROR_NATIVE_WINDOW_IN_USE_KHR, "VK_ERROR_NATIVE_WINDOW_IN_USE_KHR")
		.put(VK_SUBOPTIMAL_KHR, "VK_SUBOPTIMAL_KHR")
		.put(VK_ERROR_OUT_OF_DATE_KHR, "VK_ERROR_OUT_OF_DATE_KHR")
		.put(VK_ERROR_INCOMPATIBLE_DISPLAY_KHR, "VK_ERROR_INCOMPATIBLE_DISPLAY_KHR")
		.put(VK_ERROR_VALIDATION_FAILED_EXT, "VK_ERROR_VALIDATION_FAILED_EXT")
		.put(VK_ERROR_INVALID_SHADER_NV, "VK_ERROR_INVALID_SHADER_NV")
		.put(VK_ERROR_IMAGE_USAGE_NOT_SUPPORTED_KHR, "VK_ERROR_IMAGE_USAGE_NOT_SUPPORTED_KHR")
		.put(VK_ERROR_VIDEO_PICTURE_LAYOUT_NOT_SUPPORTED_KHR, "VK_ERROR_VIDEO_PICTURE_LAYOUT_NOT_SUPPORTED_KHR")
		.put(VK_ERROR_VIDEO_PROFILE_OPERATION_NOT_SUPPORTED_KHR, "VK_ERROR_VIDEO_PROFILE_OPERATION_NOT_SUPPORTED_KHR")
		.put(VK_ERROR_VIDEO_PROFILE_FORMAT_NOT_SUPPORTED_KHR, "VK_ERROR_VIDEO_PROFILE_FORMAT_NOT_SUPPORTED_KHR")
		.put(VK_ERROR_VIDEO_PROFILE_CODEC_NOT_SUPPORTED_KHR, "VK_ERROR_VIDEO_PROFILE_CODEC_NOT_SUPPORTED_KHR")
		.put(VK_ERROR_VIDEO_STD_VERSION_NOT_SUPPORTED_KHR, "VK_ERROR_VIDEO_STD_VERSION_NOT_SUPPORTED_KHR")
		.put(VK_ERROR_INVALID_DRM_FORMAT_MODIFIER_PLANE_LAYOUT_EXT, "VK_ERROR_INVALID_DRM_FORMAT_MODIFIER_PLANE_LAYOUT_EXT")
		.put(VK_ERROR_FULL_SCREEN_EXCLUSIVE_MODE_LOST_EXT, "VK_ERROR_FULL_SCREEN_EXCLUSIVE_MODE_LOST_EXT")
		.put(VK_THREAD_IDLE_KHR, "VK_THREAD_IDLE_KHR")
		.put(VK_THREAD_DONE_KHR, "VK_THREAD_DONE_KHR")
		.put(VK_OPERATION_DEFERRED_KHR, "VK_OPERATION_DEFERRED_KHR")
		.put(VK_OPERATION_NOT_DEFERRED_KHR, "VK_OPERATION_NOT_DEFERRED_KHR")
		.put(VK_ERROR_INVALID_VIDEO_STD_PARAMETERS_KHR, "VK_ERROR_INVALID_VIDEO_STD_PARAMETERS_KHR")
		.put(VK_ERROR_COMPRESSION_EXHAUSTED_EXT, "VK_ERROR_COMPRESSION_EXHAUSTED_EXT")
		.put(VK_INCOMPATIBLE_SHADER_BINARY_EXT, "VK_INCOMPATIBLE_SHADER_BINARY_EXT")
		.put(VK_PIPELINE_BINARY_MISSING_KHR, "VK_PIPELINE_BINARY_MISSING_KHR")
		.put(VK_ERROR_NOT_ENOUGH_SPACE_KHR, "VK_ERROR_NOT_ENOUGH_SPACE_KHR")
		.build();

	private static final Set<Integer> WARNING = Set.of(
		VK_INCOMPLETE,
		VK_SUBOPTIMAL_KHR,
		VK_THREAD_IDLE_KHR,
		VK_THREAD_DONE_KHR,
		VK_OPERATION_NOT_DEFERRED_KHR,
		VK_PIPELINE_COMPILE_REQUIRED
	);

	private static final Set<Integer> RECOVERABLE = Set.of(
		VK_TIMEOUT,
		VK_NOT_READY,
		VK_EVENT_SET,
		VK_EVENT_RESET,

		VK_ERROR_OUT_OF_DATE_KHR,
		VK_ERROR_SURFACE_LOST_KHR,
		VK_ERROR_FULL_SCREEN_EXCLUSIVE_MODE_LOST_EXT,

		VK_ERROR_NATIVE_WINDOW_IN_USE_KHR,

		VK_ERROR_VIDEO_PICTURE_LAYOUT_NOT_SUPPORTED_KHR,
		VK_ERROR_VIDEO_PROFILE_OPERATION_NOT_SUPPORTED_KHR,
		VK_ERROR_VIDEO_PROFILE_FORMAT_NOT_SUPPORTED_KHR,
		VK_ERROR_VIDEO_PROFILE_CODEC_NOT_SUPPORTED_KHR,
		VK_ERROR_VIDEO_STD_VERSION_NOT_SUPPORTED_KHR,

		VK_ERROR_INVALID_VIDEO_STD_PARAMETERS_KHR,

		VK_ERROR_IMAGE_USAGE_NOT_SUPPORTED_KHR,

		VK_ERROR_COMPRESSION_EXHAUSTED_EXT,

		VK_ERROR_INVALID_SHADER_NV,
		VK_INCOMPATIBLE_SHADER_BINARY_EXT,

		VK_ERROR_INVALID_DRM_FORMAT_MODIFIER_PLANE_LAYOUT_EXT,

		VK_PIPELINE_BINARY_MISSING_KHR,
		VK_ERROR_NOT_ENOUGH_SPACE_KHR
	);

	private static final Set<Integer> FATAL = Set.of(
		VK_ERROR_DEVICE_LOST,

		VK_ERROR_INITIALIZATION_FAILED,
		VK_ERROR_INCOMPATIBLE_DRIVER,

		VK_ERROR_OUT_OF_HOST_MEMORY,
		VK_ERROR_OUT_OF_DEVICE_MEMORY,
		VK_ERROR_MEMORY_MAP_FAILED,

		VK_ERROR_LAYER_NOT_PRESENT,
		VK_ERROR_EXTENSION_NOT_PRESENT,
		VK_ERROR_FEATURE_NOT_PRESENT,

		VK_ERROR_TOO_MANY_OBJECTS,
		VK_ERROR_FORMAT_NOT_SUPPORTED,
		VK_ERROR_FRAGMENTED_POOL,

		VK_ERROR_OUT_OF_POOL_MEMORY,

		VK_ERROR_INVALID_EXTERNAL_HANDLE,
		VK_ERROR_INVALID_OPAQUE_CAPTURE_ADDRESS,

		VK_ERROR_FRAGMENTATION,

		VK_ERROR_VALIDATION_FAILED_EXT
	);

	public static boolean isSuccess(int result) {
		return result == VK_SUCCESS;
	}

	public static boolean isWarning(int result) {
		return WARNING.contains(result);
	}

	public static boolean isRecoverable(int result) {
		return RECOVERABLE.contains(result);
	}

	public static boolean isFatal(int result) {
		return FATAL.contains(result);
	}

	@NotNull
	public static String toString(int result) {
		String name = NAMES.get(result);
		if (name == null)
			return Hex.toHex(result, 8);

		return name;
	}
}
